TRUNCATE TABLE crre.type_campaign;
INSERT INTO crre.type_campaign (id, name, credit, reassort, catalog, automatic_close, structure) VALUES (1, 'Type numérique', 'licences', false, 'Catalogue numérique', false, '[{"libelle":"Numériques"}, {"libelle":"Mixtes"}]');
INSERT INTO crre.type_campaign (id, name, credit, reassort, catalog, automatic_close, structure) VALUES (2, 'Type papier', 'licences', false, 'Catalogue papier', false, '[{"libelle":"Papier"}, {"libelle":"Mixtes"}]');
INSERT INTO crre.type_campaign( id, name, credit, reassort, catalog, automatic_close, structure) VALUES (3, 'Type consommables papier', 'consumable_licences', false, 'Catalogue papier consommable', false, '[{"libelle":"Papier"}, {"libelle":"Mixtes"}]');
INSERT INTO crre.type_campaign( id, name, credit, reassort, catalog, automatic_close, structure) VALUES (4, 'Type consommables numérique', 'consumable_licences', false, 'Catalogue numérique consommable', false, '[{"libelle":"Numériques"}, {"libelle":"Mixtes"}]');
INSERT INTO crre.type_campaign( id, name, credit, reassort, catalog, automatic_close, structure) VALUES (5, 'Type Pro papier', 'licences', false, 'Catalogue papier Pro', false, '[{"libelle":"Papier"}, {"libelle": "Établissements professionnels"}, {"libelle":"Mixtes"}]');
INSERT INTO crre.type_campaign( id, name, credit, reassort, catalog, automatic_close, structure) VALUES (6, 'Type Pro numérique', 'licences', false, 'Catalogue numérique Pro', false, '[{"libelle":"Numériques"}, {"libelle": "Établissements professionnels"}, {"libelle":"Mixtes"}]');
INSERT INTO crre.type_campaign( id, name, credit, reassort, catalog, automatic_close, structure) VALUES (7, 'Type LGT papier', 'licences', false, 'Catalogue papier LGT', false, '[{"libelle":"Papier"}, {"libelle": "Établissements généraux"}, {"libelle":"Mixtes"}]');
INSERT INTO crre.type_campaign( id, name, credit, reassort, catalog, automatic_close, structure) VALUES (8, 'Type LGT numérique', 'licences', false, 'Catalogue numérique LGT', false, '[{"libelle":"Numériques"}, {"libelle": "Établissements généraux"}, {"libelle":"Mixtes"}]');
INSERT INTO crre.type_campaign( id, name, credit, reassort, catalog, automatic_close, structure) VALUES (9, 'Type Pro consommables papier', 'consumable_licences', false, 'Catalogue consommable Pro', false, '[{"libelle":"Papier"}, {"libelle":"Mixtes"}, {"libelle": "Établissements professionnels"}]');
INSERT INTO crre.type_campaign( id, name, credit, reassort, catalog, automatic_close, structure) VALUES (10, 'Type Pro consommables numérique', 'consumable_licences', false, 'Catalogue consommable Pro', false, '[{"libelle":"Numériques"}, {"libelle":"Mixtes"}, {"libelle": "Établissements professionnels"}]')