GRANT USAGE ON SCHEMA crre TO "apps";
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA crre TO "apps";
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA crre TO "apps";
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA crre TO "apps";