GRANT USAGE ON SCHEMA crre TO "apps";
ALTER DEFAULT PRIVILEGES IN SCHEMA crre GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON TABLES TO "apps";
ALTER DEFAULT PRIVILEGES IN SCHEMA crre GRANT EXECUTE ON FUNCTIONS TO "apps";
ALTER DEFAULT PRIVILEGES IN SCHEMA crre GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO "apps";