package fr.openent.crre.core.constants;

public class Field {

    public static final String MAIL = "mail";
    public static final String EQUIPEMENT = "equipment";
    public static final String CONTENT = "content";
    public static final String NB_ETAB = "nbEtab";
    public static final String NB_ORDER = "nbOrder";
    public static final String ADDRESS = "address";
    public static final String CSVFILE = "csvFile";
    public static final String ORDER_CLIENT_EQUIPMENT = "order_client_equipment";
    public static final String ID_STRUCTURE = "id_structure";
    public static final String DESCRIPTION = "description";
    public static final String STRUCTURES = "structures";
    public static final String _ID = "_id";
    public static final String METADATA = "metadata";
    public static final String FILENAME = "filename";
    public static final String MESSAGE = "message";
    public static final String BASKET = "basket";
    public static final String CAMPAIGN = "campaign";
    public static final String USERNAME = "username";
    public static final String PASSWORD = "password";
    public static final String ELASTICSEARCHCONFIG = "elasticsearchConfig";
    public static final String API_DASH_KEY = "api-key";
    public static final String EMAILCONFIG = "emailConfig";
    public static final String PAGE = "page";
    public static final String IDCAMPAIGN = "idCampaign";
    public static final String STARTDATE = "startDate";
    public static final String ENDDATE = "endDate";
    public static final String OLD = "old";
    public static final String ID_CAMPAIGN = "id_campaign";
    public static final String NAME_CAMPAIGN = "name_campaign";
    public static final String NAME_USER = "name_user";
    public static final String ID_USER = "id_user";
    public static final String TOTAL = "total";
    public static final String AMOUNT = "amount";
    public static final String CREATED = "created";
    public static final String PROCESSING_DATE = "processing_date";
    public static final String ID_ITEM = "id_item";
    public static final String COMMENT = "comment";
    public static final String PRICE_PROPOSAL = "price_proposal";
    public static final String ID_TYPE = "id_type";
    public static final String OWNER_ID = "owner_id";
    public static final String OWNER_NAME = "owner_name";
    public static final String REASSORT = "reassort";
    public static final String IDSTRUCTURE = "idStructure";
    public static final String EQUIPMENT = "equipment";
    public static final String Q = "q";
    public static final String UTF_DASH_8 = "UTF-8";
    public static final String IDBASKET = "idBasket";
    public static final String BASKETTOORDER = "basketToOrder";
    public static final String STRUCTURE_NAME = "structure_name";
    public static final String BASKET_NAME = "basket_name";
    public static final String ID_ORDER = "id_order";
    public static final String BASKETS = "baskets";
    public static final String SPACE_CHARACTER = " ";
    public static final String ORDERS = "orders";
    public static final String PRICETTC = "priceTTC";
    public static final String PRICE = "price";
    public static final String EQUIPMENT_KEY = "equipment_key";
    public static final String NONE = "none";
    public static final String USE_CREDIT = "use_credit";
    public static final String CREATION_DATE = "creation_date";
    public static final String MODIFICATION_DATE = "modification_date";
    public static final String CAUSE_STATUS = "cause_status";
    public static final String ID_PROJECT = "id_project";
    public static final String ID_OFFER_EQUIPMENT = "id_offer_equipment";
    public static final String ID_ORDER_CLIENT_EQUIPMENT = "id_order_client_equipment";
    public static final String USER_NAME = "user_name";
    public static final String USER_ID = "user_id";
    public static final String IN_PROGRESS = "IN_PROGRESS";
    public static final String ROW_TO_JSON = "row_to_json";
    public static final String IDPROJET = "idProject";
    public static final String ID_BASKET = "id_basket";
    public static final String IDS = "ids";
    public static final String ARRAY_TO_JSON = "array_to_json";
    public static final String PROJECT = "project";
    public static final String DATA = "data";
    public static final String U = "u";
    public static final String PREFERENCES = "preferences";
    public static final Object LANGUAGE = "language";
    public static final String DEFAULT_DASH_DOMAIN = "default-domain";
    public static final String USERID = "userId";
    public static final String PUSHNOTIF = "pushNotif";
    public static final String BODY = "body";
    public static final String DISABLEMAILNOTIFICATION = "disableMailNotification";
    public static final String DISABLEANTIFLOOD = "disableAntiFlood";
    public static final String JUSTIFICATION = "justification";
    public static final String REJECTED = "REJECTED";
    public static final String FR = "fr";

    private Field() {
        throw new IllegalStateException("Utility class");
    }

    public static final String STATUS = "status";
    public static final String ID = "id";
    public static final String OK = "ok";
    public static final String ERROR = "error";
    public static final String rejected = "rejected";
    public static final String resubmit = "resubmit";
    public static final String NAME = "name";
    public static final String TITLE = "title";
    public static final String PROJECT_TITLE = "project_title";

}